"""init

Revision ID: bf7626c03509
Revises: 
Create Date: 2026-08-03 22:07:02.138247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7626c03509'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('condition', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefits_card_name'), 'benefits', ['card_name'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('merchant', sa.String(length=100), nullable=False),
    sa.Column('benefit_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_events_merchant'), 'payment_events', ['merchant'], unique=False)
    op.create_index(op.f('ix_payment_events_payment_type'), 'payment_events', ['payment_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(length=100), nullable=False),
    sa.Column('card_type', sa.String(length=50), nullable=False),
    sa.Column('current_performance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('required_performance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    op.drop_table('users')
    op.drop_index(op.f('ix_payment_events_payment_type'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_merchant'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_benefits_card_name'), table_name='benefits')
    op.drop_table('benefits')
    # ### end Alembic commands ###
